#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color \#ff80ab
bspc config focused_border_color \#6200ea
bspc config presel_feedback_color \#6200ea

bspc config top_padding 3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Follow del raton
bspc config focus_follows_pointer true

#Wallpaper
feh --bg-fill ~/Pictures/wp7196410-2217941651.jpeg

#Polybar
~/.config/polybar/./launch.sh

#Bordeados
picom --experimental-backends &

#Cursor Fix
xsetroot -cursor_name left_ptr &

#Pulseaudio launch
pulseaudio --start
